#!/usr/bin/env zsh
# Regular-file wrapper (replaces the template's symlink, which breaks when
# the repo is checked out/committed on Windows).
FORMATTER_NAME=swift exec zsh "${0:A:h}/.run-format.zsh" "$@"
